# This is a basic workflow that is manually triggered

name: Make AdiBags-Addon

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  adibags-creator:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Processing
        uses: ./ # Uses an action in the root directory
        id: processing
        env:
          BLIZZ_ID: ${{ secrets.BLIZZ_ID }}
          BLIZZ_SECRET: ${{ secrets.BLIZZ_SECRET }}
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
          # CLI arguments
          args: --verify --indent-type spaces --indent-width 2 --line-endings Windows --quote-style AutoPreferDouble out/AdiBags_REPLACENAME.lua out/Localization.lua
      - name: Luacheck Main Addon
        uses: lunarmodules/luacheck@v0
        with:
          args: out/AdiBags_REPLACENAME.lua --ignore 113 211 212 611 614 631
          # ignored (see https://luacheck.readthedocs.io/en/stable/warnings.html):
          # 113: Accessing an undefined global variable. - There are bound to be some as this an addon, as there are some functions which are known to WoW only.
          # 211: Unused local variable. - Not important.
          # 212: Unused argument. - Not important.
          # 611: A line consists of nothing but whitespace. - Oh no! Oh wait, not important.
          # 614: Trailing whitespace in a comment. - These reports are just plain wrong.
          # 631: Line is too long. - Not important.
      - name: Luacheck Localization
        uses: lunarmodules/luacheck@v0
        with:
          args: out/Localization.lua --ignore 113 211 212 542 611 614 631
          # additionally ignored:
          # 542: empty if branch - This is expected, since Bigwigs will replace the empty branch AFTER this check runs.


